mods:
  - screepsmod-auth
  - screepsmod-admin-utils
  - screepsmod-mongo
bots:
  simplebot: screepsbot-zeswarm
  overmind: screeps-bot-overmind
  tooangel: git+https://github.com/TooAngel/screeps
  commiebot: the-international-screeps-bot
