version: "3"
services:
  screeps:
    image: ghcr.io/jomik/screeps-server:edge
    depends_on:
      - mongo
      - redis
    ports:
      - 21025:21025/tcp
    volumes:
      - ./config.yml:/screeps/config.yml
      - screeps-data:/data
      - screeps-mods:/screeps/mods
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      STEAM_KEY: ${STEAM_KEY:?"Missing steam key"}
      MAPTOOL_USER: ${MAPTOOL_USER}
      MAPTOOL_PASS: ${MAPTOOL_PASS}
    restart: unless-stopped
    build: .

  mongo:
    image: mongo:4.4.18
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    command: --appendonly yes --save ''

volumes:
  screeps-data:
  screeps-mods:
  redis-data:
  mongo-data:
