name: Release to Docker Hub

on:
  push:
    paths:
      - "mods/**"
      - "Dockerfile"
    tags:
      - "v*.*.*"
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=edge,branch=main
            type=ref,event=pr
            type=semver,pattern={{major}}
            type=sha
      - name: Docker meta mongo
        id: meta-mongo
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=auto
            suffix=-mongo,onlatest=true
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=edge,branch=main
            type=ref,event=pr
            type=semver,pattern={{major}}
            type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:buildcache,mode=max
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push mongo flavor
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            NPM_MODS=screepsmod-mongo
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:buildcache
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-mongo.outputs.tags }}
          labels: ${{ steps.meta-mongo.outputs.labels }}
